version: '3'
services: 
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes: 
      - ./src:/var/www/src
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./src:/var/www/src
